name: Build and Deploy Desktop
on:
  push:
    branches:
      - main-disabled
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: pomodoro, platform: linux/amd64, os: ubuntu-latest},
          {name: pomodoro, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install and Build
        run: |
          npm install -g pnpm
          
      - uses: dAppServer/wails-build-action@main
        with:
          go-version: 1.25
          node-version: 22.19.0
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true